@host = http://localhost:3001
@contentType = application/json
@userId = 5

### Sample GET request
GET {{host}}/users/

### Sample POST request
POST {{host}}/users/
Content-Type: {{contentType}}

{
  "firstName": "Oliver",
  "lastName": "Atom"
}

### Sample POST request
DELETE {{host}}/users/{{userId}}