@host = http://localhost:3001
@contentType = application/json
@userId = 10

### Sample GET request
GET {{host}}/users/

### Sample POST request
POST {{host}}/users/
Content-Type: {{contentType}}

{
  "firstName": "Oliver",
  "lastName": "Atom"
}

### Sample DELETE request
DELETE {{host}}/users/{{userId}}

### Sample soft remove request
DELETE {{host}}/users/{{userId}}/soft

### Sample soft remove restore request
GET {{host}}/users/restore/{{userId}}